### ISSUE TITLE
Bump DO-Kubernetes to v1.16

### ISSUE THREAD

**Issue by mjuric** [dirac-institute/genesis-platform#5]
Once https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1444 is resolved, bump the allowed k8s version to 1.16.

**Comment by consideRatio** [comment]
ping @mjuric - It works on k8s 1.16 now according to our CI system, but so far untested in the real world. I'd appreciate some feedback if you try it, my environment is on k8s 1.14

**Comment by mjuric** [comment]
@consideRatio Thanks!

Confirming it worked on Digital Ocean's k8s v1.16, with one glitch -- the progress updates while a user's pod is starting seems to be gone. Instead, I get repeated 'Server requested' messages:
![image](https://user-images.githubusercontent.com/620059/69799086-72a69b80-1187-11ea-8c35-7bc95b3a5eb6.png)
until the pod finally launches and I'm redirected to `/tree`.

Regression in kubespawner, or a known issue?

Using `jupyterhub/k8s-hub:0.9.0-alpha.1.058.002ae04` for the hub (default in the `0.9.0-alpha.1.060.6698eb9` helm chart).

**Comment by mjuric** [comment]
I can confirm the same "Server requested"... issue appears on k8s 1.15, when using the `0.9.0-alpha.1.060.6698eb9` version of the helm chart. Rolling back to `0.9.0-alpha.1.028.00bc15c` chart restores the normal behavior.

**Comment by consideRatio** [comment]
Any logs from the hub pod about issues from the spawner?
