### ISSUE TITLE
Variable expansion / manipulation in *.sht with cp_with_subst

### ISSUE THREAD

**Issue by stevenstetzler** [dirac-institute/genesis-platform#7]
I am wondering if there's a way to manipulate bash variables in the template `.sht` files. For example, I'd like to replace "." with "-" in the names of launched nodes (e.g. m5.large --> m5-large, this is required for safety with nodegroup naming). I would like to do, for example:

```
# file: test.yaml.sht
name: ${SIZE//./-}
```
however this will get expanded to the literal expression `${SIZE//./-}` by `cp_with_subst`. I can get around this by creating a new variable or altering an existing one in the `config.sh.aws` file that is an altered version of the variable, like so:
```
# file: config.sh.aws
SIZE=m5.large
NODE_POOL_NAME=\${SIZE//./-}
```
and
```
# file: test.yaml.sht
name: $NODE_POOL_NAME
```
which will give correctly 
```
# file: test.yaml
name: m5-large
```

**Comment by mjuric** [comment]
I think you'd want to change the code around:

https://github.com/genesis-platform/genesis-jupyterhub-automator/blob/master/bin/_common.sh#L99

to properly capture the text within `${}`, and `eval` the whole captured thing rather than just do a replacement with the value of the variable.

**Comment by mjuric** [comment]
But it may be better to use the workaround you described, and take care of this if/when `./configure` is [rewritten in Python](https://github.com/genesis-platform/genesis-jupyterhub-automator/issues/3) (at which point we could use proper Jinja templates).

**Comment by mjuric** [comment]
Closing as wontfix as the workaround seems good enough.
